export { default as Header } from './Header'
export { default as Paner } from './Paner'
export { default as Posts } from './Posts'
export { default as Loading } from './Loading'
export { default as PageNotFound } from './PageNotFound'