// import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { Header, Paner, Posts } from '@components/index';
import { sanityClient } from '@sanity';
import { Post } from '@typing';
interface Props {
   posts: Post[];
}
function Home({ posts }: Props) {
   console.log(process.env.NEXT_PUBLIC_SANITY_PROJECT_ID)
   return (
      <div className="max-w-7xl mx-auto">
         <Head>
            <title>Blog Techology</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>
         <Header />
         <Paner />
         <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3 md:gap-6 md:p-7 p-2">
            {posts.map((post) => (
               <Posts key={post._id} post={post} />
            ))}
         </div>
      </div>
   );
}
export default Home;

export const getServerSideProps = async () => {
   const query = `*[_type=="post"]{
      _id,
      title,
      description,
      slug,
      author -> {
      name,
      image,
    },
      mainImage,
      categories,
      publishedAt,
    }`;
   const posts: any = await sanityClient.fetch(query);
   return await {
      props: { posts },
   };
};
